version: '3'

services:
  db:
    image: postgres:12
    tty: true
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-foodies}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    # do not expose any ports to host machine, only promopal container can communicate directly with the db

  promopal:
    # since there is both build and image, will build image using specified options in Dockerfile
    # and name the image promopal with tag latest
    build: .
    image: ericrkuo/promopal:latest
    ports:
      - '8000:8000'
    # will start db service first before starting promopal service
    depends_on:
      - db
    environment:
      # docker has built in DNS server that uses container name to resolve IP address. So we can use container name as host
      DB_HOST: db
