version: '3'

volumes:
    db:

services:
    db:
        image: postgres:12
        tty: true
        volumes:
          - ./tmp/db:/var/lib/postgresql/data
          - ./db:/db
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PASSWORD: admin
          PGPASSWORD: admin
          POSTGRES_USER: admin
          POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
          POSTGRES_DB: foodies
        hostname: localhost
        restart: always
        ports:
          - "5432:5432"
    web:
        build: ./backend
        image: foodies:latest
        volumes:
          - ./backend:/foodies/backend
        ports:
          - "8000:8000"
        command: bash -c "yarn install && yarn start"
        restart: always
        depends_on: 
          - db
        links: 
          - db